sudo: required
services:
  - docker

before_install:
  - docker build -t fmtech2014/react-test -f ./client/Dockerfile.dev ./client

script:
  - script:
  - docker run -e CI=true fmtech2014/react-test npm test

after_success:
  - docker build -t fmtech2014/multi-client ./client
  - docker build -t fmtech2014/multi-nginx ./nginx
  - docker build -t fmtech2014/multi-server ./server
  - docker build -t fmtech2014/multi-worker ./worker

  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push fmtech2014/multi-client
  - docker push fmtech2014/multi-nginx
  - docker push fmtech2014/multi-server
  - docker push fmtech2014/multi-worker
